// src/ide/blockly/esp32-blocks.js

import * as Blockly from 'blockly/core';

export function registerEsp32Blocks() {

'use strict';

(() => {
    // --- UNCHANGED: PIN LISTS ---
    const DIGITAL_PINS_INPUT = [
        ["2", "2"], ["4", "4"], ["5", "5"], ["12", "12"], ["13", "13"], ["14", "14"],
        ["15", "15"], ["16", "16"], ["17", "17"], ["18", "18"], ["19", "19"], ["21", "21"],
        ["22", "22"], ["23", "23"], ["25", "25"], ["26", "26"], ["27", "27"], ["32", "32"],
        ["33", "33"], ["34", "34"], ["35", "35"], ["36", "36"], ["39", "39"]
    ];
    const DIGITAL_PINS_OUTPUT = [
        ["2", "2"], ["4", "4"], ["5", "5"], ["12", "12"], ["13", "13"], ["14", "14"],
        ["15", "15"], ["16", "16"], ["17", "17"], ["18", "18"], ["19", "19"], ["21", "21"],
        ["22", "22"], ["23", "23"], ["25", "25"], ["26", "26"], ["27", "27"]
    ];
    const ADC_PINS = [
        ["32", "32"], ["33", "33"], ["34", "34"], ["35", "35"], ["36", "36"], ["39", "39"]
    ];
    const PWM_PINS = DIGITAL_PINS_OUTPUT;
    const ESP32_I2C_PINS = [
        ["SDA:21, SCL:22", "21"], ["SDA:25, SCL:26", "25"],
        ["SDA:32, SCL:33", "32"], ["SDA:18, SCL:19", "18"],
        ["SDA:4, SCL:5", "4"]
    ];
    
    // --- MODIFIED: ALL BLOCKS UPDATED TO USE NEW FIELDS ---
    const blockDefinitions = [
        // GPIO Blocks
        { "type": "gpio_digital_read", "message0": "digital read pin %1", "args0": [{ "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_INPUT, "columns": "5" }], "output": "Boolean", "style": "gpio_blocks" },
        { "type": "gpio_digital_write", "message0": "digital write to pin %1 state %2", "args0": [ { "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_OUTPUT, "columns": "5" }, { "type": "field_dropdown", "name": "STATE", "options": [["HIGH", "1"], ["LOW", "0"]] } ], "previousStatement": null, "nextStatement": null, "style": "gpio_blocks" },
        { "type": "gpio_analog_read", "message0": "analog read pin %1", "args0": [{ "type": "field_grid_dropdown", "name": "PIN", "options": ADC_PINS, "columns": "3" }], "output": "Number", "style": "gpio_blocks" },
        { "type": "gpio_pwm_write", "message0": "analog write (PWM) to pin %1 with value %2", "args0": [ { "type": "field_grid_dropdown", "name": "PIN", "options": PWM_PINS, "columns": "5" }, { "type": "input_value", "name": "VALUE", "check": "Number", "shadow": { "type": "field_slider", "fields": { "NUM": 128 }, "min": 0, "max": 255 } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "gpio_blocks" },
        { "type": "gpio_on_pin_change", "message0": "when pin %1 value changes to %2", "args0": [ { "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_INPUT, "columns": "5" }, { "type": "field_dropdown", "name": "TRIGGER", "options": [["rising edge (LOW to HIGH)", "IRQ_RISING"], ["falling edge (HIGH to LOW)", "IRQ_FALLING"]] } ], "message1": "do %1", "args1": [{ "type": "input_statement", "name": "DO" }], "style": "gpio_blocks" },
        
        // Sensor Blocks
        { "type": "sensor_dht11", "message0": "read %1 from DHT11 pin %2", "args0": [ { "type": "field_dropdown", "name": "READING", "options": [["temperature", "temperature"], ["humidity", "humidity"]] }, { "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_OUTPUT, "columns": "5" } ], "output": "Number", "style": "sensor_blocks" },
        { "type": "sensor_dht_measure", "message0": "measure temperature and humidity from DHT11 pin %1", "args0": [{ "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_OUTPUT, "columns": "5" }], "previousStatement": null, "nextStatement": null, "style": "sensor_blocks" },
        { "type": "sensor_ultrasonic_hcsr04", "message0": "ultrasonic distance in %1 trig pin %2 echo pin %3", "args0": [ { "type": "field_dropdown", "name": "UNIT", "options": [["cm", "CM"], ["inches", "INCHES"]] }, { "type": "field_grid_dropdown", "name": "TRIG_PIN", "options": DIGITAL_PINS_OUTPUT, "columns": "5" }, { "type": "field_grid_dropdown", "name": "ECHO_PIN", "options": DIGITAL_PINS_INPUT, "columns": "5" } ], "output": "Number", "style": "sensor_blocks" },
        { "type": "sensor_pir_motion", "message0": "motion detected on PIR pin %1", "args0": [{ "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_INPUT, "columns": "5" }], "output": "Boolean", "style": "sensor_blocks" },
        { "type": "sensor_limit_switch", "message0": "button/switch on pin %1 is pressed", "args0": [{ "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_INPUT, "columns": "5" }], "output": "Boolean", "style": "sensor_blocks" },
        { "type": "sensor_analog_percent", "message0": "read %1 value (%%) from pin %2", "args0": [ { "type": "field_dropdown", "name": "SENSOR_TYPE", "options": [ ["light level", "LDR"], ["soil moisture", "SOIL"], ["potentiometer", "POT"] ]}, { "type": "field_grid_dropdown", "name": "PIN", "options": ADC_PINS, "columns": "3" } ], "output": "Number", "style": "sensor_blocks" },
        { "type": "sensor_ir_obstacle", "message0": "obstacle detected on IR pin %1", "args0": [{ "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_INPUT, "columns": "5" }], "output": "Boolean", "style": "sensor_blocks" },

        // Actuator Blocks
        { "type": "actuator_led", "message0": "turn LED on pin %1 %2", "args0": [ { "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_OUTPUT, "columns": "5" }, { "type": "field_dropdown", "name": "STATE", "options": [["ON", "1"], ["OFF", "0"]] } ], "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_led_toggle", "message0": "toggle LED on pin %1", "args0": [{ "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_OUTPUT, "columns": "5" }], "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_buzzer_note", "message0": "play note %1 on buzzer pin %2 for %3 ms", "args0": [ { "type": "field_dropdown", "name": "NOTE", "options": [ ["C4", "262"], ["D4", "294"], ["E4", "330"], ["F4", "349"], ["G4", "392"], ["A4", "440"], ["B4", "494"], ["C5", "523"] ]}, { "type": "field_grid_dropdown", "name": "PIN", "options": PWM_PINS, "columns": "5" }, { "type": "input_value", "name": "DURATION", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 500 } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_servo_positional", "message0": "set servo on pin %1 to angle %2", "args0": [ { "type": "field_grid_dropdown", "name": "PIN", "options": PWM_PINS, "columns": "5" }, { "type": "field_angle", "name": "ANGLE", "angle": 90, "min": 0, "max": 180 } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_servo_continuous", "message0": "run continuous servo on pin %1 at speed %2 %%", "args0": [ { "type": "field_grid_dropdown", "name": "PIN", "options": PWM_PINS, "columns": "5" }, { "type": "field_slider", "name": "SPEED", "min": -100, "max": 100, "value": 0 } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_neopixel_setup", "message0": "setup NeoPixel strip on pin %1 with %2 pixels", "args0": [ { "type": "field_grid_dropdown", "name": "PIN", "options": DIGITAL_PINS_OUTPUT, "columns": "5" }, { "type": "input_value", "name": "NUM_PIXELS", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 8 } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_neopixel_brightness", "message0": "set NeoPixel brightness to %1 %%", "args0": [{ "type": "field_slider", "name": "BRIGHTNESS", "value": 50, "min": 0, "max": 100 }], "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        
        // Display Blocks
        { "type": "display_oled_setup", "message0": "setup OLED display on I2C pins %1", "args0": [{ "type": "field_grid_dropdown", "name": "PINS", "options": ESP32_I2C_PINS, "columns": "1" }], "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        
        // Wi-Fi Blocks
        { "type": "wifi_send_web_response", "message0": "send web response with HTML %1", "args0": [{ "type": "input_value", "name": "HTML", "check": "String", "shadow": { "type": "text_multiline", "fields": { "TEXT": "<h1>Hello from ESP32</h1>" } } }], "previousStatement": null, "nextStatement": null, "style": "networking_blocks" },


        { "type": "async_sleep_ms", "message0": "await sleep for %1 ms", "args0": [{ "type": "input_value", "name": "MS", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 100 } } }], "previousStatement": null, "nextStatement": null, "style": "loops_blocks" },
        { "type": "async_run_main_loop", "message0": "run async tasks", "nextStatement": null, "style": "loops_blocks", "deletable": false },
        { "type": "sensor_internal_temp", "message0": "read internal temperature in %1", "args0": [{ "type": "field_dropdown", "name": "UNIT", "options": [["°C", "C"], ["°F", "F"]] }], "output": "Number", "style": "sensor_blocks" },
        { "type": "actuator_onboard_led", "message0": "turn onboard LED (pin 2) %1", "args0": [{ "type": "field_dropdown", "name": "STATE", "options": [["ON", "1"], ["OFF", "0"]] }], "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_buzzer_tone", "message0": "play tone at %1 Hz on buzzer pin %2 for %3 ms", "args0": [ { "type": "input_value", "name": "FREQ", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 440 } } }, { "type": "field_grid_dropdown", "name": "PIN", "options": PWM_PINS, "columns": "5" }, { "type": "input_value", "name": "DURATION", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 500 } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        
        { "type": "actuator_neopixel_fill", "message0": "fill NeoPixel strip with color %1", "args0": [{ "type": "input_value", "name": "COLOR", "check": "Colour", "shadow": { "type": "colour_picker", "fields": { "COLOUR": "#ff0000" }}}], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_neopixel_set", "message0": "set NeoPixel # %1 to color %2", "args0": [ { "type": "input_value", "name": "PIXEL_NUM", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } }, { "type": "input_value", "name": "COLOR", "check": "Colour", "shadow": { "type": "colour_picker", "fields": { "COLOUR": "#ff0000" }}}], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        
        { "type": "actuator_neopixel_shift", "message0": "shift pixels by %1 positions", "args0": [{ "type": "input_value", "name": "SHIFT", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 1 } } }], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_neopixel_rainbow", "message0": "advance rainbow effect by one step", "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_neopixel_show", "message0": "show NeoPixel changes", "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "actuator_neopixel_clear", "message0": "clear NeoPixel strip", "previousStatement": null, "nextStatement": null, "style": "actuator_blocks" },
        { "type": "display_oled_show", "message0": "show OLED changes", "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_clear", "message0": "clear OLED display", "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_power", "message0": "turn OLED display %1", "args0": [{ "type": "field_dropdown", "name": "STATE", "options": [["ON", "poweron"], ["OFF", "poweroff"]] }], "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_contrast", "message0": "set OLED contrast to %1", "args0": [{ "type": "input_value", "name": "CONTRAST", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 255 } } }], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_invert", "message0": "invert OLED colors %1", "args0": [{ "type": "field_dropdown", "name": "INVERT", "options": [["ON", "1"], ["OFF", "0"]] }], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_text", "message0": "on OLED, print %1 at x %2 y %3", "args0": [ { "type": "input_value", "name": "TEXT", "shadow": { "type": "text", "fields": { "TEXT": "Hello" } } }, { "type": "input_value", "name": "X", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } }, { "type": "input_value", "name": "Y", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_pixel", "message0": "draw pixel at x %1 y %2 color %3", "args0": [ { "type": "input_value", "name": "X", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 10 } } }, { "type": "input_value", "name": "Y", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 10 } } }, { "type": "field_dropdown", "name": "COLOR", "options": [["ON", "1"], ["OFF", "0"]] } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_line", "message0": "draw line from x1 %1 y1 %2 to x2 %3 y2 %4", "args0": [ { "type": "input_value", "name": "X1", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } }, { "type": "input_value", "name": "Y1", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } }, { "type": "input_value", "name": "X2", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 127 } } }, { "type": "input_value", "name": "Y2", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 63 } } } ], "inputsInline": false, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_rect", "message0": "%1 rectangle at x %2 y %3 width %4 height %5", "args0": [ { "type": "field_dropdown", "name": "MODE", "options": [["draw", "rect"], ["fill", "fill_rect"]] }, { "type": "input_value", "name": "X", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 10 } } }, { "type": "input_value", "name": "Y", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 10 } } }, { "type": "input_value", "name": "WIDTH", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 20 } } }, { "type": "input_value", "name": "HEIGHT", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 15 } } } ], "inputsInline": false, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_animate_fireworks", "message0": "run fireworks animation for %1 seconds", "args0": [{ "type": "input_value", "name": "DURATION", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 5 } } }], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "display_oled_create_image", "message0": "create image width %1 height %2", "message1": "from bytearray data %1", "args0": [ { "type": "input_value", "name": "WIDTH", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 16 } } }, { "type": "input_value", "name": "HEIGHT", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 16 } } } ], "args1": [{ "type": "input_value", "name": "DATA", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "" } } }], "output": "Image", "style": "display_blocks", "inputsInline": true },
        { "type": "display_oled_draw_image", "message0": "draw image %1 at x %2 y %3", "args0": [ { "type": "input_value", "name": "IMAGE", "check": "Image" }, { "type": "input_value", "name": "X", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } }, { "type": "input_value", "name": "Y", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "display_blocks" },
        { "type": "usb_serial_println", "message0": "USB Serial print line %1", "args0": [{ "type": "input_value", "name": "DATA", "check": ["String", "Number", "Boolean"], "shadow": { "type": "text", "fields": { "TEXT": "Hello" } } }], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "communication_blocks" },
        { "type": "usb_serial_print_value", "message0": "USB Serial print value %1 = %2", "args0": [ { "type": "input_value", "name": "NAME", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "Value" } } }, { "type": "input_value", "name": "VALUE", "check": ["String", "Number", "Boolean"], "shadow": { "type": "math_number", "fields": { "NUM": 0 } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "communication_blocks" },
        { "type": "usb_serial_read_line", "message0": "USB Serial read line", "output": "String", "style": "communication_blocks" },
        { "type": "usb_serial_plot_value", "message0": "plot value %1 with name %2 using color %3", "args0": [ { "type": "input_value", "name": "VALUE", "check": "Number", "shadow": { "type": "math_number", "fields": { "NUM": 0 } } }, { "type": "input_value", "name": "NAME", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "Sensor" } } }, { "type": "field_colour_hsv_sliders", "name": "COLOR", "colour": "#5a67d8" } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "communication_blocks" },
        { "type": "comm_send_ai_command", "message0": "send AI command to IDE %1 with parameter %2", "args0": [ { "type": "field_dropdown", "name": "COMMAND", "options": [ ["Toggle Camera", "toggle_camera"], ["Turn Camera ON", "camera_on"], ["Turn Camera OFF", "camera_off"], ["Monitor Face Landmarks", "monitor_face"], ["Monitor Hand Gestures", "monitor_hand"], ["Monitor Object Detection", "monitor_detection"], ["Monitor Image Classification", "monitor_classification"], ["Stop Monitoring", "monitor_stop"] ] }, { "type": "input_value", "name": "PARAM", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "" } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "communication_blocks" },
        { "type": "wifi_connect", "message0": "connect to Wi-Fi network %1 password %2", "args0": [ { "type": "input_value", "name": "SSID", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "my_ssid" } } }, { "type": "input_value", "name": "PASSWORD", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "password" } } } ], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "networking_blocks" },
        { "type": "wifi_is_connected", "message0": "is Wi-Fi connected?", "output": "Boolean", "style": "networking_blocks" },
        { "type": "wifi_get_ip", "message0": "get Wi-Fi IP address", "output": "String", "style": "networking_blocks" },
        { "type": "http_get_json", "message0": "get JSON data from URL %1", "args0": [{ "type": "input_value", "name": "URL", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "https://api.example.com/data" } } }], "output": "Dictionary", "style": "networking_blocks" },
        { "type": "json_get_key", "message0": "from JSON data %1 get value of key %2", "args0": [ { "type": "input_value", "name": "JSON", "check": "Dictionary" }, { "type": "input_value", "name": "KEY", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "key_name" } } } ], "output": null, "style": "networking_blocks" },
        { "type": "http_post_json", "message0": "send data to webhook URL %1", "message1": "value1 %1", "message2": "value2 %1", "message3": "value3 %1", "args0": [{ "type": "input_value", "name": "URL", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "https://maker.ifttt.com/..." } } }], "args1": [{ "type": "input_value", "name": "VALUE1", "shadow": { "type": "text", "fields": { "TEXT": "" } } }], "args2": [{ "type": "input_value", "name": "VALUE2", "shadow": { "type": "text", "fields": { "TEXT": "" } } }], "args3": [{ "type": "input_value", "name": "VALUE3", "shadow": { "type": "text", "fields": { "TEXT": "" } } }], "previousStatement": null, "nextStatement": null, "style": "networking_blocks" },
        { "type": "wifi_start_web_server", "message0": "start web server in background", "previousStatement": null, "nextStatement": null, "style": "networking_blocks" },
        { "type": "wifi_on_web_request", "message0": "when a web browser connects", "message1": "do %1", "args1": [{ "type": "input_statement", "name": "DO" }], "style": "networking_blocks" },
        { "type": "wifi_get_web_request_path", "message0": "get URL path from web request", "output": "String", "style": "networking_blocks" },
        { "type": "ble_setup", "message0": "setup Bluetooth LE with name %1", "args0": [{ "type": "input_value", "name": "NAME", "check": "String", "shadow": { "type": "text", "fields": { "TEXT": "MyESP32-BLE" } } }], "previousStatement": null, "nextStatement": null, "style": "bluetooth_blocks" },
        { "type": "ble_advertise_data", "message0": "advertise Bluetooth LE data %1", "args0": [{ "type": "input_value", "name": "DATA", "shadow": { "type": "text", "fields": { "TEXT": "Hello" } } }], "inputsInline": true, "previousStatement": null, "nextStatement": null, "style": "bluetooth_blocks" }
    ];
    
    Blockly.defineBlocksWithJsonArray(blockDefinitions);
})();

}